//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.06 at 07:17:04 PM UTC 
//


package Trees;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Add complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Add"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="2" minOccurs="2"&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Add" type="{}Add"/&gt;
 *           &lt;element name="Sub" type="{}Sub"/&gt;
 *           &lt;element name="Mul" type="{}Mul"/&gt;
 *           &lt;element name="Div" type="{}Div"/&gt;
 *           &lt;element name="Num" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Add" type="{}Add"/&gt;
 *           &lt;element name="Sub" type="{}Sub"/&gt;
 *           &lt;element name="Mul" type="{}Mul"/&gt;
 *           &lt;element name="Div" type="{}Div"/&gt;
 *           &lt;element name="Num" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Add", propOrder = {
    "addOrSubOrMul"
})
public class Add {

    @XmlElements({
        @XmlElement(name = "Add", type = Add.class),
        @XmlElement(name = "Sub", type = Sub.class),
        @XmlElement(name = "Mul", type = Mul.class),
        @XmlElement(name = "Div", type = Div.class),
        @XmlElement(name = "Num", type = Long.class)
    })
    protected List<Object> addOrSubOrMul;

    /**
     * Gets the value of the addOrSubOrMul property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addOrSubOrMul property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddOrSubOrMul().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Add }
     * {@link Sub }
     * {@link Mul }
     * {@link Div }
     * {@link Long }
     * 
     * 
     */
    public List<Object> getAddOrSubOrMul() {
        if (addOrSubOrMul == null) {
            addOrSubOrMul = new ArrayList<Object>();
        }
        return this.addOrSubOrMul;
    }

}
