//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.06 at 07:17:04 PM UTC 
//


package Trees;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Add" type="{}Add"/&gt;
 *         &lt;element name="Sub" type="{}Sub"/&gt;
 *         &lt;element name="Mul" type="{}Mul"/&gt;
 *         &lt;element name="Div" type="{}Div"/&gt;
 *         &lt;element name="Num" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "add",
    "sub",
    "mul",
    "div",
    "num"
})
@XmlRootElement(name = "Tree")
public class Tree {

    @XmlElement(name = "Add")
    protected Add add;
    @XmlElement(name = "Sub")
    protected Sub sub;
    @XmlElement(name = "Mul")
    protected Mul mul;
    @XmlElement(name = "Div")
    protected Div div;
    @XmlElement(name = "Num")
    protected Long num;

    /**
     * Gets the value of the add property.
     * 
     * @return
     *     possible object is
     *     {@link Add }
     *     
     */
    public Add getAdd() {
        return add;
    }

    /**
     * Sets the value of the add property.
     * 
     * @param value
     *     allowed object is
     *     {@link Add }
     *     
     */
    public void setAdd(Add value) {
        this.add = value;
    }

    /**
     * Gets the value of the sub property.
     * 
     * @return
     *     possible object is
     *     {@link Sub }
     *     
     */
    public Sub getSub() {
        return sub;
    }

    /**
     * Sets the value of the sub property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sub }
     *     
     */
    public void setSub(Sub value) {
        this.sub = value;
    }

    /**
     * Gets the value of the mul property.
     * 
     * @return
     *     possible object is
     *     {@link Mul }
     *     
     */
    public Mul getMul() {
        return mul;
    }

    /**
     * Sets the value of the mul property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mul }
     *     
     */
    public void setMul(Mul value) {
        this.mul = value;
    }

    /**
     * Gets the value of the div property.
     * 
     * @return
     *     possible object is
     *     {@link Div }
     *     
     */
    public Div getDiv() {
        return div;
    }

    /**
     * Sets the value of the div property.
     * 
     * @param value
     *     allowed object is
     *     {@link Div }
     *     
     */
    public void setDiv(Div value) {
        this.div = value;
    }

    /**
     * Gets the value of the num property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNum() {
        return num;
    }

    /**
     * Sets the value of the num property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNum(Long value) {
        this.num = value;
    }

}
